-- =====================================================================
-- SIGMA ACADEMIC LEARNING PLATFORM - SUPABASE POSTGRESQL SCHEMA
-- =====================================================================
-- Run this script in your Supabase SQL Editor to initialize your production
-- database tables. This schema maps exactly to the cryptographic user state 
-- and auditing framework generated by your Express/React application.

-- 1. Create the Users Table
CREATE TABLE IF NOT EXISTS public.users (
    uid VARCHAR(128) PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(64) NOT NULL, -- SHA-256 string
    streak INT DEFAULT 1,
    gems INT DEFAULT 100,
    tier VARCHAR(20) DEFAULT 'scholar', -- 'scholar' | 'analyst' | 'magnate'
    billing_cycle VARCHAR(20) DEFAULT 'monthly', -- 'monthly' | 'annual'
    avatar_seed VARCHAR(30) NOT NULL,
    active_title VARCHAR(128) DEFAULT '',
    sponsored_count INT DEFAULT 0,
    unlocked_items JSONB DEFAULT '[]'::jsonb,
    progress JSONB DEFAULT '{
      "personalFinance": {"level": 1, "progressPercent": 0, "completedLevels": {}},
      "accounting": {"level": 1, "progressPercent": 0, "completedLevels": {}},
      "statistics": {"level": 1, "progressPercent": 0, "completedLevels": {}},
      "appliedMath": {"level": 1, "progressPercent": 0, "completedLevels": {}}
    }'::jsonb,
    unlocked_levels JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable indexes for fast lookup and login matching
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);

-- 2. Create the Security Logs Table
CREATE TABLE IF NOT EXISTS public.security_logs (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    action VARCHAR(100) NOT NULL,
    details TEXT NOT NULL,
    encrypted_payload_preview TEXT,
    decrypted_verification BOOLEAN DEFAULT TRUE
);

-- Index on security log timestamps for rapid audit analysis
CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON public.security_logs(timestamp DESC);

-- 3. Create the Entries Table (Accounting Ledger Entries for Simulator)
CREATE TABLE IF NOT EXISTS public.entries (
    id BIGSERIAL PRIMARY KEY,
    description TEXT NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('debit', 'credit')),
    account VARCHAR(20) NOT NULL CHECK (account IN ('cash', 'equipment', 'loans', 'equity')),
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index on created_at for fast time-series ordering
CREATE INDEX IF NOT EXISTS idx_entries_created_at ON public.entries(created_at ASC);

-- =====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================
-- Since the Express server acts as a secure cryptographic gatekeeper proxy,
-- it will bypass standard user-level RLS using the Supabase SERVICE_ROLE API key to ensure 
-- that raw client transmission decryption and hashing are always performed server-side.
-- However, we can enforce RLS to ensure clients cannot access files publically.

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entries ENABLE ROW LEVEL SECURITY;

-- Allow read/write access strictly to the service_role bypass or define specific policies
CREATE POLICY "Bypass RLS for Server Admin" ON public.users 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Bypass RLS for Logs Admin" ON public.security_logs 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Bypass RLS for Entries Admin" ON public.entries 
    FOR ALL USING (true) WITH CHECK (true);
